name: CI

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]

  workflow_dispatch:

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ["22.x", "23.x", "24.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:coverage

      - name: Upload coverage to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.node == '22.x'
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.node == '22.x'
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
          verbose: true

      - name: Build
        run: pnpm build

  release:
    name: Release

    if: ${{ github.ref == 'refs/heads/master' }}

    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Release
        run: pnpm semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.SEMANTIC_RELEASE_GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SEMANTIC_RELEASE_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SEMANTIC_RELEASE_GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SEMANTIC_RELEASE_GIT_EMAIL }}
